import 'package:isar/isar.dart';

// Generated by build_runner: `dart run build_runner build`.
part 'project.g.dart';

/// A project folder ("Channel"/"Folder" in the dashboard) that groups related
/// scripts, e.g. "YouTube Longform", "Shorts & TikTok", "Podcast Outlines".
@collection
class Project {
  Id id = Isar.autoIncrement;

  /// Stable cross-store identifier used for navigation & linking scripts.
  @Index(unique: true)
  late String uuid;

  late String title;
  String? description;

  @Enumerated(EnumType.name)
  ProjectType type = ProjectType.other;

  late DateTime createdAt;
  late DateTime updatedAt;

  @Index()
  bool isArchived = false;

  Project();

  Project.create({
    required this.uuid,
    required this.title,
    this.description,
    this.type = ProjectType.other,
  })  : createdAt = DateTime.now(),
        updatedAt = DateTime.now();
}

enum ProjectType {
  youtubeLongform,
  shorts,
  podcast,
  videoEssay,
  other;

  String get label => switch (this) {
        ProjectType.youtubeLongform => 'YouTube Longform',
        ProjectType.shorts => 'Shorts & TikTok',
        ProjectType.podcast => 'Podcast Outlines',
        ProjectType.videoEssay => 'Video Essay',
        ProjectType.other => 'General',
      };
}
